### ISSUE TITLE
Expected content

### ISSUE THREAD

**Issue by Becca-Saunders** [Becca-Saunders/dinosaur-designs#3]
Hopefully this is the last issue I have. 
I can't seem to figure out what is wrong with line of code. 

@hellachella
<img width="1228" alt="Screen Shot 2021-03-08 at 2 51 31 PM" src="https://user-images.githubusercontent.com/77293037/110373895-023f2900-801e-11eb-8735-be89720a488d.png">
![Screen Shot 2021-03-08 at 2 51 43 PM](https://user-images.githubusercontent.com/77293037/110373896-02d7bf80-801e-11eb-9026-940a102c439c.png)

**Comment by anna-pokhilenko** [comment]
Try putting the expected content in your title instead of _Dinosaur Design_, I guess, that's the issue

**Comment by hellachella** [comment]
You are the second person to have this annoying glitch. c/p this exact same thing in and remove that line.

`    <h1><img src="images/dinos-r-us.svg" alt="Dinos ’R’ Us"></h1>
`

**Comment by hellachella** [comment]
In the real world, this wouldn't make a difference. It's markbot. I need to find out what's up with it.

**Comment by Becca-Saunders** [comment]
> Try putting the expected content in your title instead of _Dinosaur Design_, I guess, that's the iss

**Comment by hellachella** [comment]
That should not be the issue. Not even the solution has that, but if it worked, great!!
